version: "3"

services:
  nav2:
    image: nav2-humble
    build:
      context: ../../
      dockerfile: docker/nav2_example/Dockerfile
    container_name: nav2-humble
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./gazebo_init/:/home/user/.gazebo/  # Mount Gazebo files, otherwise starting it takes ages.
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=waffle
      - GAZEBO_MODEL_PATH=/home/user/.gazebo/models:/opt/ros/humble/share/turtlebot3_gazebo/models
      - ROS_DOMAIN_ID=42  # Not to conflict with the main Task Manager
    command: ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False

  task_manager:
    image: task_manager
    build:
      context: ../../
      dockerfile: docker/task_manager/Dockerfile
    container_name: task_manager_nav2_example
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42  # Not to conflict with the main Task Manager
    volumes:
      - ../../task_manager:/ros2_ws/src/task_manager/
      - ../../task_manager_msgs:/ros2_ws/src/task_manager_msgs/
      - ../../examples:/examples/
    command: ros2 launch task_manager task_manager.launch.py params_file:=/examples/nav2_example_params.yaml
