mrs_uav_managers:

  world_origin:

    units: "LATLON" # {"UTM, "LATLON"}

    origin_x: 49.3620031
    origin_y: 14.2603156

  safety_area_manager:

    safety_area:

      enabled: true

      horizontal:

        # the frame of reference in which the points are expressed
        frame_name: "world_origin"

        # polygon
        #
        # x, y [m] for any frame_name except latlon_origin
        # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
        points: [
          -50, -50,
          50,  -50,
          50,  50,
          -50, 50,
        ]

      vertical:

        # the frame of reference in which the max&min z is expressed
        frame_name: "world_origin"

        max_z: 15.0
        min_z: 0.5

      obstacles:

        present: false
